TeethCabinet/Models/RDV.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeethCabinet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDV
    {
        public int RdvID { get; set; }
        public int PatientID { get; set; }
        public int PersonnelID { get; set; }
        public Nullable<System.DateTime> DateHeureRdv { get; set; }
        public string Motif { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}

TeethCabinet/Controllers/RDVsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TeethCabinet.Models;

namespace TeethCabinet.Controllers
{
    [Authorize]
    public class RDVsController : Controller
    {
        private TeethCabEntities db = new TeethCabEntities();

        // GET: RDVs               

        public ActionResult Index(string searchBy, string search)
        {
            var rDVs = db.RDVs.Include(r => r.Patient).Include(r => r.Personnel);

            if (searchBy == "patient")
            {
                return View(db.RDVs.Where(x => x.Patient.Nom.StartsWith(search) || search == null).ToList());
            }
            else if (searchBy == "personnel")
            {
                return View(db.RDVs.Where(x => x.Personnel.Nom.StartsWith(search) || search == null).ToList());
            }
            else

            {
                return View(db.RDVs.Where(x => x.Motif.StartsWith(search) || search == null).ToList());
            }

            //return View(rDVs.ToList());
        }

        // GET: RDVs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RDV rDV = db.RDVs.Find(id);
            if (rDV == null)
            {
                return HttpNotFound();
            }
            return View(rDV);
        }

        // GET: RDVs/Create
        public ActionResult Create()
        {
            ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "Nom");
            ViewBag.PersonnelID = new SelectList(db.Personnels, "PersonnelID", "Nom");
            return View();
        }

        // POST: RDVs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RdvID,PatientID,PersonnelID,DateHeureRdv,Motif")] RDV rDV)
        {
            if (ModelState.IsValid)
            {
                db.RDVs.Add(rDV);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "Nom", rDV.PatientID);
            ViewBag.PersonnelID = new SelectList(db.Personnels, "PersonnelID", "Nom", rDV.PersonnelID);
            return View(rDV);
        }

        // GET: RDVs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RDV rDV = db.RDVs.Find(id);
            if (rDV == null)
            {
                return HttpNotFound();
            }
            ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "Nom", rDV.PatientID);
            ViewBag.PersonnelID = new SelectList(db.Personnels, "PersonnelID", "Nom", rDV.PersonnelID);
            return View(rDV);
        }

        // POST: RDVs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RdvID,PatientID,PersonnelID,DateHeureRdv,Motif")] RDV rDV)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rDV).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "Nom", rDV.PatientID);
            ViewBag.PersonnelID = new SelectList(db.Personnels, "PersonnelID", "Nom", rDV.PersonnelID);
            return View(rDV);
        }

        // GET: RDVs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RDV rDV = db.RDVs.Find(id);
            if (rDV == null)
            {
                return HttpNotFound();
            }
            return View(rDV);
        }

        // POST: RDVs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RDV rDV = db.RDVs.Find(id);
            db.RDVs.Remove(rDV);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TeethCabinet/Views/RDVs/Create.cshtml
@model TeethCabinet.Models.RDV

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RDV</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PatientID, "PatientID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PatientID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PatientID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonnelID, "PersonnelID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonnelID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonnelID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateHeureRdv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateHeureRdv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateHeureRdv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Motif, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Motif, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Motif, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TeethCabinet/Views/RDVs/Delete.cshtml
@model TeethCabinet.Models.RDV

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RDV</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateHeureRdv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateHeureRdv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Motif)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Motif)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patient.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personnel.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personnel.Nom)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TeethCabinet/Views/RDVs/Details.cshtml
@model TeethCabinet.Models.RDV

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>RDV</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateHeureRdv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateHeureRdv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Motif)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Motif)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patient.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Personnel.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Personnel.Nom)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RdvID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TeethCabinet/Views/RDVs/Edit.cshtml
@model TeethCabinet.Models.RDV

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RDV</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RdvID)

        <div class="form-group">
            @Html.LabelFor(model => model.PatientID, "PatientID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PatientID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PatientID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonnelID, "PersonnelID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonnelID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonnelID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateHeureRdv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateHeureRdv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateHeureRdv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Motif, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Motif, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Motif, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TeethCabinet/Views/RDVs/Index.cshtml
@model IEnumerable<TeethCabinet.Models.RDV>

@{
    ViewBag.Title = "Index";
}

<h2>RDVs</h2>

<div>
    @using (Html.BeginForm("Index", "RDVs", FormMethod.Get))
    {

        @Html.RadioButton("searchBy", "Motif", true) <text> Motif</text>
        @Html.RadioButton("searchBy", "patient") <text> patient</text>
        @Html.RadioButton("searchBy", "personnel") <text> personnel</text><br />
        @Html.TextBox("search", null, new { @class = "form-control" });
        <button type="submit" class="btn btn-primary">Chercher</button>
    }

</div>
<br />


<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DateHeureRdv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Motif)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Patient.Nom) patient
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Personnel.Nom) personnel
        </th>
        <th></th>
    </tr>

    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="4">Aucune ligne ne corresond aux criteres de recherche</td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DateHeureRdv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Motif)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Patient.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Personnel.Nom)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.RdvID }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Details", "Details", new { id = item.RdvID }, new { @class = "btn btn-info" })
                    @Html.ActionLink("Delete", "Delete", new { id = item.RdvID }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }

    }

</table>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
</p>