TeethCabinet/Models/Patient.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeethCabinet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Consultations = new HashSet<Consultation>();
            this.RDVs = new HashSet<RDV>();
        }
    
        public int PatientID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Addresse { get; set; }
        public string Email { get; set; }
        public string NumTel { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public string Sexe { get; set; }
        public string NumSS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultation> Consultations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDV> RDVs { get; set; }
    }
}

TeethCabinet/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TeethCabinet.Models;
using System.Data;
using System.Data.Entity;
using System.Net;



namespace TeethCabinet.Controllers
{
    [Authorize]
    public class PatientsController : Controller
    {
        private TeethCabEntities dbMod = new TeethCabEntities();
        // GET: Patients
        public ActionResult Index(string searchBy, string search)
        {
            if (searchBy == "Sexe")
            {
                return View(dbMod.Patients.Where(x => x.Sexe.StartsWith(search) || search == null).ToList());
            }
            else if (searchBy == "NumSS")
            {
                return View(dbMod.Patients.Where(x => x.NumSS.StartsWith(search) || search == null).ToList());
            }

            else if (searchBy == "Addresse")
            {
                return View(dbMod.Patients.Where(x => x.Addresse.StartsWith(search) || search == null).ToList());
            }

            else

            {
                return View(dbMod.Patients.Where(x => x.Nom.StartsWith(search) || search == null).ToList());
            }
        }

        // GET: Patients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = dbMod.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // GET: Patients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Patients/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PatientID,Nom,Prenom,Addresse,Email,NumTel,DateNaissance,Sexe,NumSS")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                dbMod.Patients.Add(patient);
                dbMod.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(patient);
        }

        // GET: Patients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = dbMod.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);

        }

        // POST: Patients/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PatientID,Nom,Prenom,Addresse,Email,NumTel,DateNaissance,Sexe,NumSS")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                dbMod.Entry(patient).State = EntityState.Modified;
                dbMod.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        // GET: Patients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = dbMod.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Delete/5        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Patient patient = dbMod.Patients.Find(id);
            dbMod.Patients.Remove(patient);
            dbMod.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                dbMod.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TeethCabinet/Views/Patients/Create.cshtml
@model TeethCabinet.Models.Patient

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Patient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prenom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prenom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prenom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Addresse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Addresse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Addresse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumTel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumTel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumTel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateNaissance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateNaissance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateNaissance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumSS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumSS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumSS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TeethCabinet/Views/Patients/Delete.cshtml
@model TeethCabinet.Models.Patient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Addresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Addresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumTel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumTel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumSS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumSS)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TeethCabinet/Views/Patients/Details.cshtml
@model TeethCabinet.Models.Patient

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Addresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Addresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumTel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumTel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumSS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumSS)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PatientID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TeethCabinet/Views/Patients/Edit.cshtml
@model TeethCabinet.Models.Patient

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Patient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PatientID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prenom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prenom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prenom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Addresse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Addresse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Addresse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumTel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumTel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumTel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateNaissance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateNaissance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateNaissance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumSS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumSS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumSS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TeethCabinet/Views/Patients/Index.cshtml
@model IEnumerable<TeethCabinet.Models.Patient>
    @{
    ViewBag.Title = "Index";
    }
    <h2>Patients</h2>
    <div>
        @using (Html.BeginForm("Index", "Patients", FormMethod.Get))
        {

        @Html.RadioButton("searchBy", "Nom", true) <text> Nom</text>
        @Html.RadioButton("searchBy", "Sexe") <text> Sexe</text>
        @Html.RadioButton("searchBy", "NumSS") <text> NumSS</text>
        @Html.RadioButton("searchBy", "Addresse") <text> Addresse</text><br />
        @Html.TextBox("search", null, new { @class = "form-control" });
        <button type="submit" class="btn btn-primary">Chercher</button>
        }

    </div>
    <br />
    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prenom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Addresse)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumTel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateNaissance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexe)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumSS)
            </th>
            <th></th>
        </tr>

        @if (Model.Count() == 0)
        {
        <tr>
            <td colspan="9">Aucune ligne ne corresond aux criteres de recherche</td>
        </tr>
        }
        else

        {
        foreach (var item in Model)
        {
        <tr class="table-">
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prenom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Addresse)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumTel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateNaissance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumSS)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.PatientID }, new { @class = "btn btn-warning" })
                @Html.ActionLink("Details", "Details", new { id = item.PatientID }, new { @class = "btn btn-info" })
                @Html.ActionLink("Delete", "Delete", new { id = item.PatientID }, new { @class = "btn btn-danger" })
            </td>
        </tr>
        }
        }
    </table>
    <p>
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
    </p>